const indianUniversities = [
  // IITs
  { name: 'IIT Bombay', type: 'IIT', location: 'Mumbai, Maharashtra' },
  { name: 'IIT Delhi', type: 'IIT', location: 'New Delhi, Delhi' },
  { name: 'IIT Madras', type: 'IIT', location: 'Chennai, Tamil Nadu' },
  { name: 'IIT Kanpur', type: 'IIT', location: 'Kanpur, Uttar Pradesh' },
  { name: 'IIT Kharagpur', type: 'IIT', location: 'Kharagpur, West Bengal' },
  { name: 'IIT Roorkee', type: 'IIT', location: 'Roorkee, Uttarakhand' },
  { name: 'IIT Guwahati', type: 'IIT', location: 'Guwahati, Assam' },
  { name: 'IIT Hyderabad', type: 'IIT', location: 'Hyderabad, Telangana' },
  { name: 'IIT Indore', type: 'IIT', location: 'Indore, Madhya Pradesh' },
  { name: 'IIT Jodhpur', type: 'IIT', location: 'Jodhpur, Rajasthan' },
  { name: 'IIT Patna', type: 'IIT', location: 'Patna, Bihar' },
  { name: 'IIT Ropar', type: 'IIT', location: 'Rupnagar, Punjab' },
  { name: 'IIT Bhubaneswar', type: 'IIT', location: 'Bhubaneswar, Odisha' },
  { name: 'IIT Gandhinagar', type: 'IIT', location: 'Gandhinagar, Gujarat' },
  { name: 'IIT Mandi', type: 'IIT', location: 'Mandi, Himachal Pradesh' },
  { name: 'IIT Palakkad', type: 'IIT', location: 'Palakkad, Kerala' },
  { name: 'IIT Tirupati', type: 'IIT', location: 'Tirupati, Andhra Pradesh' },
  { name: 'IIT Dhanbad', type: 'IIT', location: 'Dhanbad, Jharkhand' },
  { name: 'IIT Bhilai', type: 'IIT', location: 'Bhilai, Chhattisgarh' },
  { name: 'IIT Goa', type: 'IIT', location: 'Goa' },
  { name: 'IIT Jammu', type: 'IIT', location: 'Jammu, Jammu & Kashmir' },
  { name: 'IIT Dharwad', type: 'IIT', location: 'Dharwad, Karnataka' },

  // NITs
  { name: 'NIT Trichy', type: 'NIT', location: 'Tiruchirappalli, Tamil Nadu' },
  { name: 'NIT Warangal', type: 'NIT', location: 'Warangal, Telangana' },
  { name: 'NIT Surathkal', type: 'NIT', location: 'Surathkal, Karnataka' },
  { name: 'NIT Calicut', type: 'NIT', location: 'Calicut, Kerala' },
  { name: 'NIT Allahabad', type: 'NIT', location: 'Allahabad, Uttar Pradesh' },
  { name: 'NIT Bhopal', type: 'NIT', location: 'Bhopal, Madhya Pradesh' },
  { name: 'NIT Jalandhar', type: 'NIT', location: 'Jalandhar, Punjab' },
  { name: 'NIT Jaipur', type: 'NIT', location: 'Jaipur, Rajasthan' },
  { name: 'NIT Kurukshetra', type: 'NIT', location: 'Kurukshetra, Haryana' },
  { name: 'NIT Rourkela', type: 'NIT', location: 'Rourkela, Odisha' },
  { name: 'NIT Silchar', type: 'NIT', location: 'Silchar, Assam' },
  { name: 'NIT Srinagar', type: 'NIT', location: 'Srinagar, Jammu & Kashmir' },
  { name: 'NIT Hamirpur', type: 'NIT', location: 'Hamirpur, Himachal Pradesh' },
  { name: 'NIT Jamshedpur', type: 'NIT', location: 'Jamshedpur, Jharkhand' },
  { name: 'NIT Patna', type: 'NIT', location: 'Patna, Bihar' },
  { name: 'NIT Raipur', type: 'NIT', location: 'Raipur, Chhattisgarh' },
  { name: 'NIT Agartala', type: 'NIT', location: 'Agartala, Tripura' },
  { name: 'NIT Arunachal Pradesh', type: 'NIT', location: 'Yupia, Arunachal Pradesh' },
  { name: 'NIT Manipur', type: 'NIT', location: 'Imphal, Manipur' },
  { name: 'NIT Meghalaya', type: 'NIT', location: 'Shillong, Meghalaya' },
  { name: 'NIT Mizoram', type: 'NIT', location: 'Aizawl, Mizoram' },
  { name: 'NIT Nagaland', type: 'NIT', location: 'Dimapur, Nagaland' },
  { name: 'NIT Puducherry', type: 'NIT', location: 'Karaikal, Puducherry' },
  { name: 'NIT Sikkim', type: 'NIT', location: 'Ravangla, Sikkim' },
  { name: 'NIT Uttarakhand', type: 'NIT', location: 'Srinagar, Uttarakhand' },

  // Other Top Universities
  { name: 'BITS Pilani', type: 'Private', location: 'Pilani, Rajasthan' },
  { name: 'BITS Goa', type: 'Private', location: 'Goa' },
  { name: 'BITS Hyderabad', type: 'Private', location: 'Hyderabad, Telangana' },
  { name: 'VIT Vellore', type: 'Private', location: 'Vellore, Tamil Nadu' },
  { name: 'SRM University', type: 'Private', location: 'Chennai, Tamil Nadu' },
  { name: 'Manipal Institute of Technology', type: 'Private', location: 'Manipal, Karnataka' },
  { name: 'Thapar University', type: 'Private', location: 'Patiala, Punjab' },
  { name: 'Delhi Technological University', type: 'State', location: 'New Delhi, Delhi' },
  { name: 'Netaji Subhas University of Technology', type: 'State', location: 'New Delhi, Delhi' },
  { name: 'PES University', type: 'Private', location: 'Bangalore, Karnataka' },
  { name: 'RVCE Bangalore', type: 'Private', location: 'Bangalore, Karnataka' },
  { name: 'MS Ramaiah Institute of Technology', type: 'Private', location: 'Bangalore, Karnataka' },
  { name: 'College of Engineering Pune', type: 'State', location: 'Pune, Maharashtra' },
  { name: 'VJTI Mumbai', type: 'State', location: 'Mumbai, Maharashtra' },
  { name: 'Jadavpur University', type: 'State', location: 'Kolkata, West Bengal' },
  { name: 'Anna University', type: 'State', location: 'Chennai, Tamil Nadu' },
  { name: 'Osmania University', type: 'State', location: 'Hyderabad, Telangana' },
  { name: 'University of Mumbai', type: 'State', location: 'Mumbai, Maharashtra' },
  { name: 'University of Delhi', type: 'State', location: 'New Delhi, Delhi' },
  { name: 'University of Calcutta', type: 'State', location: 'Kolkata, West Bengal' },
  { name: 'University of Madras', type: 'State', location: 'Chennai, Tamil Nadu' },
  { name: 'University of Pune', type: 'State', location: 'Pune, Maharashtra' },
  { name: 'University of Hyderabad', type: 'Central', location: 'Hyderabad, Telangana' },
  { name: 'JNU Delhi', type: 'Central', location: 'New Delhi, Delhi' },
  { name: 'BHU Varanasi', type: 'Central', location: 'Varanasi, Uttar Pradesh' },
  { name: 'Aligarh Muslim University', type: 'Central', location: 'Aligarh, Uttar Pradesh' },
  { name: 'Jamia Millia Islamia', type: 'Central', location: 'New Delhi, Delhi' },
  { name: 'Other', type: 'Other', location: 'India' }
];

const csMajors = [
  'Computer Science and Engineering',
  'Computer Science',
  'Information Technology',
  'Computer Engineering',
  'Software Engineering',
  'Data Science',
  'Artificial Intelligence',
  'Machine Learning',
  'Cybersecurity',
  'Computer Science and Information Technology',
  'Computer Science and Business Systems',
  'Computer Science and Design',
  'Computer Science and Artificial Intelligence',
  'Computer Science and Engineering (AI & ML)',
  'Computer Science and Engineering (Data Science)',
  'Computer Science and Engineering (Cybersecurity)',
  'Computer Science and Engineering (IoT)',
  'Computer Science and Engineering (Blockchain)',
  'Computer Science and Engineering (Cloud Computing)',
  'Computer Science and Engineering (DevOps)',
  'Computer Science and Engineering (Game Development)',
  'Computer Science and Engineering (Mobile Computing)',
  'Computer Science and Engineering (Web Technologies)',
  'Computer Science and Engineering (Big Data)',
  'Computer Science and Engineering (Robotics)',
  'Computer Science and Engineering (Computer Vision)',
  'Computer Science and Engineering (Natural Language Processing)',
  'Computer Science and Engineering (Computer Networks)',
  'Computer Science and Engineering (Database Systems)',
  'Computer Science and Engineering (Operating Systems)',
  'Computer Science and Engineering (Compiler Design)',
  'Computer Science and Engineering (Computer Architecture)',
  'Computer Science and Engineering (Distributed Systems)',
  'Computer Science and Engineering (Parallel Computing)',
  'Computer Science and Engineering (Embedded Systems)',
  'Computer Science and Engineering (VLSI Design)',
  'Computer Science and Engineering (Digital Signal Processing)',
  'Computer Science and Engineering (Image Processing)',
  'Computer Science and Engineering (Pattern Recognition)',
  'Computer Science and Engineering (Neural Networks)',
  'Computer Science and Engineering (Fuzzy Logic)',
  'Computer Science and Engineering (Genetic Algorithms)',
  'Computer Science and Engineering (Swarm Intelligence)',
  'Computer Science and Engineering (Expert Systems)',
  'Computer Science and Engineering (Knowledge Engineering)',
  'Computer Science and Engineering (Semantic Web)',
  'Computer Science and Engineering (Grid Computing)',
  'Computer Science and Engineering (Cluster Computing)',
  'Computer Science and Engineering (Quantum Computing)',
  'Computer Science and Engineering (Bioinformatics)',
  'Computer Science and Engineering (Computational Biology)',
  'Computer Science and Engineering (Computational Chemistry)',
  'Computer Science and Engineering (Computational Physics)',
  'Computer Science and Engineering (Computational Mathematics)',
  'Computer Science and Engineering (Computational Finance)',
  'Computer Science and Engineering (Computational Linguistics)',
  'Computer Science and Engineering (Computational Geometry)',
  'Computer Science and Engineering (Computational Topology)',
  'Computer Science and Engineering (Computational Number Theory)',
  'Computer Science and Engineering (Computational Group Theory)',
  'Computer Science and Engineering (Computational Graph Theory)',
  'Computer Science and Engineering (Computational Complexity)',
  'Computer Science and Engineering (Computational Logic)',
  'Computer Science and Engineering (Computational Semantics)',
  'Computer Science and Engineering (Computational Pragmatics)',
  'Computer Science and Engineering (Computational Phonology)',
  'Computer Science and Engineering (Computational Morphology)',
  'Computer Science and Engineering (Computational Syntax)',
  'Computer Science and Engineering (Computational Discourse)',
  'Computer Science and Engineering (Computational Stylistics)',
  'Computer Science and Engineering (Computational Rhetoric)',
  'Computer Science and Engineering (Computational Poetics)',
  'Computer Science and Engineering (Computational Aesthetics)',
  'Computer Science and Engineering (Computational Creativity)',
  'Computer Science and Engineering (Computational Musicology)',
  'Computer Science and Engineering (Computational Art History)',
  'Computer Science and Engineering (Computational Archaeology)',
  'Computer Science and Engineering (Computational Anthropology)',
  'Computer Science and Engineering (Computational Sociology)',
  'Computer Science and Engineering (Computational Psychology)',
  'Computer Science and Engineering (Computational Economics)',
  'Computer Science and Engineering (Computational Political Science)',
  'Computer Science and Engineering (Computational Geography)',
  'Computer Science and Engineering (Computational History)',
  'Computer Science and Engineering (Computational Philosophy)',
  'Computer Science and Engineering (Computational Theology)',
  'Computer Science and Engineering (Computational Law)',
  'Computer Science and Engineering (Computational Medicine)',
  'Computer Science and Engineering (Computational Dentistry)',
  'Computer Science and Engineering (Computational Pharmacy)',
  'Computer Science and Engineering (Computational Nursing)',
  'Computer Science and Engineering (Computational Veterinary Medicine)',
  'Computer Science and Engineering (Computational Agriculture)',
  'Computer Science and Engineering (Computational Forestry)',
  'Computer Science and Engineering (Computational Fisheries)',
  'Computer Science and Engineering (Computational Mining)',
  'Computer Science and Engineering (Computational Petroleum)',
  'Computer Science and Engineering (Computational Nuclear)',
  'Computer Science and Engineering (Computational Solar)',
  'Computer Science and Engineering (Computational Wind)',
  'Computer Science and Engineering (Computational Hydro)',
  'Computer Science and Engineering (Computational Geothermal)',
  'Computer Science and Engineering (Computational Biomass)',
  'Computer Science and Engineering (Computational Tidal)',
  'Computer Science and Engineering (Computational Wave)',
  'Computer Science and Engineering (Computational Ocean)',
  'Computer Science and Engineering (Computational Atmospheric)',
  'Computer Science and Engineering (Computational Space)',
  'Computer Science and Engineering (Computational Planetary)',
  'Computer Science and Engineering (Computational Stellar)',
  'Computer Science and Engineering (Computational Galactic)',
  'Computer Science and Engineering (Computational Cosmological)',
  'Computer Science and Engineering (Computational Quantum)',
  'Computer Science and Engineering (Computational Relativistic)',
  'Computer Science and Engineering (Computational String)',
  'Computer Science and Engineering (Computational Loop)',
  'Computer Science and Engineering (Computational Twistor)',
  'Computer Science and Engineering (Computational Spin)',
  'Computer Science and Engineering (Computational Foam)',
  'Computer Science and Engineering (Computational Brane)',
  'Computer Science and Engineering (Computational M)',
  'Computer Science and Engineering (Computational F)',
  'Computer Science and Engineering (Computational G)',
  'Computer Science and Engineering (Computational E)',
  'Computer Science and Engineering (Computational D)',
  'Computer Science and Engineering (Computational C)',
  'Computer Science and Engineering (Computational B)',
  'Computer Science and Engineering (Computational A)',
  'Other'
];

const indianStates = [
  'Andhra Pradesh',
  'Arunachal Pradesh',
  'Assam',
  'Bihar',
  'Chhattisgarh',
  'Goa',
  'Gujarat',
  'Haryana',
  'Himachal Pradesh',
  'Jharkhand',
  'Karnataka',
  'Kerala',
  'Madhya Pradesh',
  'Maharashtra',
  'Manipur',
  'Meghalaya',
  'Mizoram',
  'Nagaland',
  'Odisha',
  'Punjab',
  'Rajasthan',
  'Sikkim',
  'Tamil Nadu',
  'Telangana',
  'Tripura',
  'Uttar Pradesh',
  'Uttarakhand',
  'West Bengal',
  'Delhi',
  'Jammu & Kashmir',
  'Ladakh',
  'Chandigarh',
  'Dadra and Nagar Haveli and Daman and Diu',
  'Lakshadweep',
  'Puducherry',
  'Andaman and Nicobar Islands'
];

const popularCities = [
  'Mumbai', 'Delhi', 'Bangalore', 'Hyderabad', 'Chennai', 'Kolkata', 'Pune',
  'Ahmedabad', 'Jaipur', 'Surat', 'Lucknow', 'Kanpur', 'Nagpur', 'Indore',
  'Thane', 'Bhopal', 'Visakhapatnam', 'Pimpri-Chinchwad', 'Patna', 'Vadodara',
  'Ghaziabad', 'Ludhiana', 'Agra', 'Nashik', 'Faridabad', 'Meerut', 'Rajkot',
  'Kalyan-Dombivali', 'Vasai-Virar', 'Varanasi', 'Srinagar', 'Aurangabad',
  'Dhanbad', 'Amritsar', 'Allahabad', 'Ranchi', 'Howrah', 'Coimbatore',
  'Jabalpur', 'Gwalior', 'Vijayawada', 'Jodhpur', 'Madurai', 'Raipur',
  'Kota', 'Guwahati', 'Chandigarh', 'Solapur', 'Hubballi-Dharwad', 'Bareilly',
  'Moradabad', 'Mysore', 'Gurgaon', 'Aligarh', 'Jalandhar', 'Tiruchirappalli',
  'Bhubaneswar', 'Salem', 'Warangal', 'Mira-Bhayandar', 'Thiruvananthapuram',
  'Bhiwandi', 'Saharanpur', 'Gorakhpur', 'Guntur', 'Bikaner', 'Amravati',
  'Noida', 'Jamshedpur', 'Bhilai', 'Cuttack', 'Firozabad', 'Kochi', 'Nellore',
  'Bhavnagar', 'Dehradun', 'Durgapur', 'Asansol', 'Rourkela', 'Nanded',
  'Kolhapur', 'Ajmer', 'Akola', 'Gulbarga', 'Jamnagar', 'Udaipur', 'Maheshtala',
  'Tirupati', 'Karnal', 'Bathinda', 'Kishanganj', 'Kurnool', 'Tirunelveli',
  'Rohtak', 'Panipat', 'Darbhanga', 'Kharagpur', 'Aizawl', 'Ichalkaranji',
  'Tiruppur', 'Karnal', 'Bathinda', 'Rampur', 'Shivamogga', 'Ratlam',
  'Modinagar', 'Delhi Cantonment', 'Pali', 'Palanpur', 'Gandhinagar',
  'Navi Mumbai', 'Thrissur', 'Gangtok', 'Imphal', 'Shillong', 'Aizawl',
  'Kohima', 'Itanagar', 'Agartala', 'Panaji', 'Puducherry', 'Kavaratti',
  'Port Blair', 'Silvassa', 'Daman', 'Diu', 'Chandigarh', 'Srinagar',
  'Leh', 'Kargil', 'Jammu', 'Katra', 'Udhampur', 'Rajouri', 'Poonch',
  'Doda', 'Kishtwar', 'Ramban', 'Reasi', 'Samba', 'Kathua', 'Bandipora',
  'Baramulla', 'Budgam', 'Ganderbal', 'Kupwara', 'Pulwama', 'Shopian',
  'Anantnag', 'Kulgam', 'Shupiyan', 'Ladakh', 'Kargil', 'Leh'
];

module.exports = {
  indianUniversities,
  csMajors,
  indianStates,
  popularCities
}; 